---
- hosts: all
  vars_files:
    - vars/main.yml
    - vars/credentials.yml

  pre_tasks:
    - name: Update cache for Debian-based distros
      apt:
        update_cache: true
      when: ansible_facts['os_family'] == 'Debian'
      changed_when: false

  roles:
    - name: Include docker role
      role: geerlingguy.docker

  tasks:
    - name: Install python dependencies
      package:
        name:
          - python3
          - python3-docker
          - python3-compose
        state: present

    - name: Create the needed directory structure
      file:
        path: "{{ workdir }}"
        state: directory
        mode: 0600
      changed_when: false

    - name: Copy chloewinkel Dockerfile directory
      copy:
        src: files/chloewinkel-dockerfile
        dest: "{{ workdir }}/.chloewinkel_dot_com/"

    - name: Copy qweebs static site Dockerfile directory
      copy:
        src: files/qweebs-static-site/
        dest: "{{ workdir }}/.qweebs-static-site"

    - name: Copy docker-compose
      template:
        src: files/docker-compose.yml
        dest: "{{ workdir }}/docker-compose.yml"
      register: deploy_file

    - name: Prepare the directory structure for traefik config
      file:
        path: "{{ workdir }}/tools/traefik"
        state: directory
        recurse: true

    - name: Copy the traefik config
      template:
        src: "files/traefik/config.yml"
        dest: "{{ workdir }}/tools/traefik/config.yml"

    - name: Create the directory structure for Prometheus
      file:
        path: "{{ workdir }}/.prometheus"
        state: directory

    - name: Copy the prometheus config
      template:
        src: "files/prometheus/prometheus.yml"
        dest: "{{ workdir }}/.prometheus/prometheus.yml"

    # TODO: Edit the docker-compose up smarted (for them to work in one command)

    - name: Upgrade the containers and run `docker-compose up`
      community.general.docker_compose:
        project_src: "{{ workdir }}"
        pull: true
        remove_orphans: true
      register: output
      when: upgrade

    - name: Run `docker-compose up`
      community.general.docker_compose:
        project_src: "{{ workdir }}"
      register: output
      when: deploy_file.changed and not upgrade
